### ISSUE TITLE
VRAM issues

### ISSUE THREAD

**Issue by osfa** [justinpinkney/stable-diffusion#15]
Hi!

The repo and finetuning tutorial mention >16GB as a minimum amount of VRAM. Has this been verified somehow?
Running this on an RTX3090 (24GB VRAM) and CUDA is still OOM:ing. 

With that result running this on Google Colab doesn't seem particularly possible?

The tutorial mentions reducing batch_size which I've done (by changing batch_size and num_workers to 1 in the pokemon.yaml conf) but still CUDA OOM.

Are there any other params one can change to reduce memory use?
Were batch_size and num_workers the correct parameters to tweak in the first place?

Thanks!

**Comment by vade** [comment]
Same here. 3x 3090, No joy.

**Comment by vade** [comment]
One thought. The environment.yaml file specifies Cuda 11.0. The 3090 requires 11.1 or better. (see https://forums.developer.nvidia.com/t/cuda-10-1-on-rtx-3090/185255/2)  

I'm not sure what the consequences are wrt the supported PyTorch and then cascading set of dependency changes that happen, but were going to try 11.1.

The forked master ( presser/stable-diffusion) has 11.0, but strangely compvis/stable-diffusion has cuda 11.3

and the Yaml file was updated a month ago, which seems to have different dependencies pinned. Just an observation, but this repo at 11.0 is likely going to be an issue for newer coda hardware.

**Comment by osfa** [comment]
Hmm yeah maybe related? I'm having these issues in an environment with 11.3 anyways.

**Comment by rsomani95** [comment]
I'm also unable to run this in an environment with 11.3.
I think the `environment.yaml` file is definitely outdated, as it mentions `pytorch=1.7.0`, which is incompatible with the dependencies inside `requirements.txt` (specifically, `kornia==0.6` requires torch > 1.8)

@justinpinkney it would be great if you could specify the torch and torchvision versions in the `requirements.txt`. 
FWIW, I tried reducing the batch size to 1, and training and validation image sizes to 128, but still got OOM errors. 

Also, I'm happy to run any tests needed to help get this running on a 3090. Any help is much appreciated. Thanks!

**Comment by justinpinkney** [comment]
Yeah the environment.yml is old an inherited from the base repo, I should get rid of that.

The version I'm using are:

```
torch==1.12.1
torchvision==0.13.1
cuda 11.3.1
```

**Comment by rsomani95** [comment]
Thanks @justinpinkney.
I setup a fresh docker container with the mentioned requirements via `docker pull pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime`, then installed deps from the `requirements.txt`. I had to uninstall `torchtext` to get the script working, but then failed with the following OOM error:

```python
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 23.70 GiB total capacity; 21.90 GiB already allocated; 13.62 MiB free; 22.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

---

I modified image size and batch size as follows:
```
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 0
    num_val_workers: 0
    train:
      target: ldm.data.simple.hf_dataset
      params:
        name: lambdalabs/pokemon-blip-captions
        image_transforms:
        - target: torchvision.transforms.Resize
          params:
            size: 64
            interpolation: 3
        - target: torchvision.transforms.RandomCrop
          params:
            size: 64
        - target: torchvision.transforms.RandomHorizontalFlip
    validation:
      target: ldm.data.simple.TextOnly
      params:
        captions:
        - A pokemon with green eyes, large wings, and a hat
        - A cute bunny rabbit
        - Yoda
        - An epic landscape photo of a mountain
        output_size: 128
        n_gpus: 1
```

But still failed with the same error. Curious if you're able to replicate this.
Any ideas how to proceed?
